version: '3'
services:
  mariadb:
    image: mariadb:latest
    environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_USER=root
    volumes:
        - ./data/db:/var/lib/mysql
  nginx:
    image: nginx
    ports:
      - "8080:80"
      - "443:443"
    links:
      - crashhub
    volumes:
      - ./data/nginx.conf:/etc/nginx/nginx.conf
  crashhub:
    build: .
    links:
      - mariadb:db
    volumes:
    - ./data/config.json:/app/config.json