version: '2'
services:
  mariadb:
    image: mariadb:latest
    environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_USER=root
    volumes:
        - ./data/db:/var/lib/mysql
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - crashhub
    volumes:
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./data/qtum.site.crt:/opt/server.crt
      - ./data/qtum.site.key:/opt/server.key
      - ./data/nginx/log:/var/log/nginx
  crashhub:
    build: .
    links:
      - mariadb:db
    volumes:
    - ./data/config.json:/app/config.json